version: '3'

tasks:
  cli:
    cmds:
      - go run ./cmd/main.go {{.CLI_ARGS}}
  build:
    cmds:
      - go build -o ./bin/witigo ./cmd/main.go
  test:
    cmds:
      - go test ./test
  basic_example:
    dir: examples/basic
    cmds:
      - cd lib && cmake --workflow --preset wasi
      - go run ./main.go ./lib/build/wasi/src/basic_example_component.wasm
