version: '3'

tasks:
  cli:
    cmds:
      - go run ./cmd/main.go {{.CLI_ARGS}}
  build:
    cmds:
      - go build -o ./bin/witigo ./cmd/main.go
  test:
    cmds:
      - go test ./pkg/abi/test
  all-types-example:
    cmds:
      - cd ./examples/all-types/lib && cmake --workflow --preset wasi
      - go run ./cmd/main.go generate ./examples/all-types/lib/build/wasi/src/all_types_example_component.wasm ./examples/all-types/generated
      - go run ./examples/all-types/main.go
