name: Test

on:
  push:

jobs:
  test:
    name: 'Test'
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
            go-version: '1.24'
            cache: 'true'

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.3'

      - name: Install Taskfile
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Run tests
        run: task test

      - name: Run basic example
        run: task basic-example

      # Disabled for now until all WIT types are supported
      # - name: Run all types example
      #   run: task all-types-example

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}